Document: pyramid-chameleon
Title: Debian pyramid-chameleon Manual
Author: <insert document author here>
Abstract: This manual describes what pyramid-chameleon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyramid-chameleon/pyramid-chameleon.sgml.gz

Format: postscript
Files: /usr/share/doc/pyramid-chameleon/pyramid-chameleon.ps.gz

Format: text
Files: /usr/share/doc/pyramid-chameleon/pyramid-chameleon.text.gz

Format: HTML
Index: /usr/share/doc/pyramid-chameleon/html/index.html
Files: /usr/share/doc/pyramid-chameleon/html/*.html
